apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}-kafka
spec:
  serviceName: "{{ .Release.Name }}-kafka-headless"
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-kafka
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-kafka
    spec:
      containers:
        - name: kafka
          image: {{ .Values.kafka.image.repository }}:{{ .Values.kafka.image.tag }}
          ports:
            - containerPort: 9093
          env:
            - name: KAFKA_ADVERTISED_LISTENER
              value: "{{ .Release.Name }}-kafka-headless:9093"
            - name: KAFKA_LISTENER_SECURITY_PROTOCOL
              value: PLAINTEXT
            - name: KAFKA_LISTENER_INTERNAL
              value: INTERNAL
            - name: KAFKA_LISTENER_PORT
              value: "9093"
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: "{{ .Release.Name }}-zookeeper-headless:2181"
          volumeMounts:
            - mountPath: /var/lib/kafka/data
              name: kafka-storage
  volumeClaimTemplates:
    - metadata:
        name: kafka-storage
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: {{ .Values.kafka.persistence.size }}
