apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}-zookeeper-pv
spec:
  capacity:
    storage: {{ .Values.zookeeper.persistence.size }}
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "{{ .Values.zookeeper.persistence.hostPath }}"
