apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-zookeeper-headless
spec:
  clusterIP: None
  selector:
    app: {{ .Release.Name }}-zookeeper
  ports:
    - port: 2181
      name: client
      targetPort: 2181
